services:
  # nginx
  web:
    build:
      dockerfile: ./nginx/Dockerfile
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  # php
  app:
    build:
      dockerfile: ./php/Dockerfile
      target: "${BUILD_TARGET:-app}"
    volumes:
      - ./app:/var/www/html
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"