services:
#ngix
  web:
    build:
      dockerfile: ./nginx/Dockerfile
      target: app
    ports:
      - "8080:80"
    volumes:
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
#php
  app:
    build:
      dockerfile: ./php/Dockerfile