services:
  # nginx
  web:
    image: garyclarke/nginx-php:1.0
    ports:
      - "8080:80"
  # php
  app:
    image: helingtonjunior/certidea-php-composer:1.0
    environment:
      REDIS_HOST: cache
      REDIS_PORT: ${REDIS_PORT}
    extra_hosts:
      - host.docker.internal:host-gateway
  # redis
  cache:
    image: redis:latest